console.log(Math.min(1,2,3,4,5))
console.log(Math.max(1,2,3,4,5))
let array = [1,2,20,4,5]
console.log(Math.min(...array))
console.log(Math.max(...array))
console.log(Math.round(45.5))
console.log(Math.round(45.49999))
console.log(Math.floor(49.9))
console.log(Math.ceil(49.1))
console.log(Math.pow(2,3))
console.log(Math.sqrt(4))
console.log(Math.cbrt(8))
console.log(Math.random())
console.log(Math.random()*2)